name: AlexCarberry
favicon: null
layout_spectrum: 0.19686591741628945
typography_spectrum: 0.4312813142314553
title: Alex Carberry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050608'
    - '#297048'
    - '#55ab88'
    - '#f37a7f'
    - '#793a4b'
  brandStrength: 0.1875
  lightness: 0.17562817805446684
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
