name: AlexCarberry
favicon: null
layout_spectrum: 0.19686591741628945
typography_spectrum: 0.4312813142314553
title: Alex Carberry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9318418267648667
  lightness: 0.17562817805446684
  saturation: 0.5660299144219607
  rhythmicContrast: 0.4751062502618879
purpose: []
