name: Alex Carberry
favicon: null
layout_spectrum: 0.33135
typography_spectrum: 0.39433
title: Alex Carberry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#94ba65'
    - '#353432'
    - '#4e4d4a'
    - '#2b4e72'
    - '#2790b0'
  brandStrength: 0.3125
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
